name: Second Workflow
on: [workflow_dispatch]
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
            - name: Install Nodejs
              uses: actions/setuo-node@v3
              with: 
                node-version: 18    
