name: Third Workflow 
on:
    workflow_dispatch:
        inputs:
            environment:
                type: environment
                required: true
                default: 'dev'
jobs:
    SetDeployEnv: 
        name: Set Development Environment
        runs-on: ubuntu-latest
        steps:
            - name: Setup Environment
              shell: bash
              run: python --version